<a href="https://colab.research.google.com/github/ustab/NOTES-FROM-LECTURERS/blob/main/DAwPy_S2_(Numpy_Concat_Split_Indexing_Selection_Operations)_%C4%B0lknur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 02</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays - Part - 02</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [CONCATENATION OF THE ARRAYS](#00)
    * [2D Matrix](#00.1)
* [SPLITTING OF THE ARRAYS](#000)
    * [2D Matrix](#000.1)
* [SORTING OF THE ARRAYS](#0000)
    * [2D Matrix](#0000.1)
* [NUMPY INDEXING & SELECTION](#1)
    * [Bracket Indexing & Selection](#1.1)
    * [Indexing a 2D Array (Matrices)](#1.2)
    * [Slicing a 2D Array (Matrices)](#1.3)
    * [Fancy Indexing](#1.4)
    * [Using Basic Index & Fancy Index Together](#1.5)
    * [Using Basic Slicing & Fancy Index Together](#1.6)
    * [More Indexing Help](#1.7)
* [SELECTION ON A CONDITION](#2)
* [BROADCASTING](#3)
* [NUMPY OPERATIONS](#4)
    * [Arithmetic Operations](#4.1)
    * [Universal Array Functions](#4.2)
    * [Statistical Calculations](#4.3)
* [OFFICIAL TUTORIAL](#5)
* [THE END OF THE SESSION-02](#6)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

**``NOTE:``** For installation instructions, please refer to the notebook at SESSION-01 (Numpy Part-01)

In [ ]:
import numpy as np

**REMINDER**<br>
NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays. In numpy dimensions are called as axes.

**Why do we need NumPy?**

A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Concatenation of the Arrays</p>

<a id="00"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this lecture we will first discuss how to concatenate, split and sort the arrays.

**``concatenate((a1, a2, ...), axis=0, out=None)``**

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [ ]:
np.concatenate([x,y])  # tek boyutlu iki veya daha fazla array'i arka arkaya birleştirir.

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([x, y, z], axis=0)  # default axis değeri 0'dır. Yani tek boyutlularda axis=0 boyunca birleştirir.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate([x, y, z], axis=1)  # tek boyutlu arraylerde axis=1 olduğu zaman hata verir.

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.concatenate([x.reshape(1,3), y.reshape(1,3), z.reshape(1,3)], axis=0)  # arraylere reshape() ile boyut kazandırırsam bu şekilde çalışır.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# ikinci yol:

np.concatenate([[x, y, z]], axis=0)  # x,y,z 'yi ikinci bir köşeli parantez içine alarak axis=0(satırlar boyunca )da birleştirme yapabiliriz.

array([array([[1, 2, 3],
              [4, 5, 6]]), array([[ 7,  8,  9],
                                  [10, 11, 12],
                                  [13, 14, 15]]), array([7, 8, 9])],
      dtype=object)

In [ ]:
# 3. yol
np.concatenate([x, y, z], axis=0).reshape(3,3)  # tek boyutlu birleştirdiğimiz arrayin şeklini değiştirerek de axis=0 boyunca birleştirme yapmış oluruz.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
[[x,y,z]]

[[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]]

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="00.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [ ]:
# iki boyutlu arraylerde concatenate yapabilmek için birleştirilecek arraylerin satır veya sütun sayıları eşit olmalı.
# Satır bazında (axis=0) birleştirme yapılacak ise sütun sayıları eşit olmalı.
# Sütun bazında (axis=1) birleştirme yapılacak ise satır sayıları eşit olmalı.
x = np.array([[1, 2, 3], [4, 5, 6]])  # 2 rows, 3 columns
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])  # 3 rows, 3 columns
x,y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [ ]:
#Ör: axis=0 bazında birleştirme yapıldığında sütun sayıları eşit ise birleştirmeyi yapar ve hata vermez.
np.concatenate([x,y], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
# Ör: axis=1 bazında birleştirme yapıldığında satır sayıları eşit dğilse birleştirmeyi yapamaz ve hata verir.

np.concatenate([x,y], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
a = np.random.randint(10, size = (2, 3))
b = np.random.randint(10, size = (2, 3))

In [ ]:
a, b

(array([[8, 5, 1],
        [5, 3, 0]]),
 array([[7, 8, 2],
        [1, 9, 5]]))

In [ ]:
np.concatenate([a,b], axis=0)  # 2,3 'lük iki arrayi axis=0 bazında birleştirince 4,3'lük bir array oluşur.

array([[8, 5, 1],
       [5, 3, 0],
       [7, 8, 2],
       [1, 9, 5]])

In [ ]:
np.concatenate([a,b], axis=1)  # 2,3 'lük iki arrayi axis=1 bazında birleştirince 2,6'lık bir array oluşur.

array([[8, 5, 1, 7, 8, 2],
       [5, 3, 0, 1, 9, 5]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Splitting of the Arrays</p>

<a id="000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**``np.split(ary, indices_or_sections, axis=0)``**

In [ ]:
x = np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [ ]:
# np.split() fonksiyonu ile bir arrayi belirttiğiniz şekilde parçalara bölebilirsiniz.

np.split(x, [3,5])  # 0:3, 3:5, 5:  şeklinde böldü

In [ ]:
a,b,c = np.split(x, [3,5])  # 0:3, 3:5, 5:  şeklinde böldüğümüz parçaları yeni birer değişkene atadık.
a,b,c

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [ ]:
np.split(x, [4])  # 0:4, 4:, şeklinde iki parçaya böldü.

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [ ]:
np.split(x, 4)  # index numarasını köşeli parantez içinde vermezsek 4 eşit parçaya böler.
# Ancak bu durumda array eleman sayısının 4'e bölünebilen bir sayı olması gerekir.

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

The number of the elements ``should be divisible`` by 4, otherwise raises an error. If the argument (here is 4) is not enclosed by square brackets, then it means dividing into 4 pieces.

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [ ]:
m = np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# İki boyutlu arraylerde split işlemi yapılırken indexlerde birlikte axis'in de belirtilmesi gerekir.

np.split(m, [1,3], axis = 0)  # axis=0 --> satırlar boyunca :1, 1:3:, 3:, şeklinde üç parçaya böldük.

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [ ]:
np.split(m, 5, axis = 0)  # axis=0 --> satırlar boyunca 5 eşit parçaya böldük.

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [ ]:
np.split(m, [1,3], axis = 1)  axis=1 --> sütunlar boyunca :1, 1:3:, 3:, şeklinde üç parçaya böldük.

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [ ]:
np.vsplit(m,[3])  # vertical split ile satırlar boyunca(axis=0 gibi) :3, 3: şeklinde iki parçaya böldük.

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [ ]:
np.hsplit(m,[3])  # horizontal split ile sütunlar boyunca (axis=1 gibi) :3,3: şeklinde iki parçaya böldük.

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Sorting of the Arrays</p>

<a id="0000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [ ]:
v = np.array([2,1,4,3,5,8,1])

In [ ]:
np.sort(v)  # sıralanmış bir array verir ancak orjinalini değiştirmez.

array([1, 1, 2, 3, 4, 5, 8])

In [ ]:
v

array([2, 1, 4, 3, 5, 8, 1])

In [ ]:
v.sort()  # bu şekilde kullanıldığında hem sıralar hem de orjinalinde bu değişikliği yapar.

In [ ]:
v

array([1, 1, 2, 3, 4, 5, 8])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="0000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [ ]:
twoD = np.random.randint(5, 100, (3,3))
twoD

array([[24, 86, 69],
       [61, 61, 18],
       [11, 19, 95]])

In [ ]:
# iki boyutlu arraylerde sıralama yaparken axis mutlaka belirtilmelidir.

np.sort(twoD, axis=0)  # axis=0 verince satırlar boyunca sıralama yapar.

array([[11, 19, 18],
       [24, 61, 69],
       [61, 86, 95]])

In [ ]:
np.sort(twoD, axis=1)  # axis=1 verince sütunlar boyunca sıralama yapar.

array([[24, 69, 86],
       [18, 61, 61],
       [11, 19, 95]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing & Selection</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this part of the lecture we will discuss how to select elements or groups of elements from an array.

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. [SOURCE](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp)

### ``Types of Indexing``

There are **``two types of indexing:``**

**``1 - Basic Slicing and indexing:``** Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :
- a slice object that is of the form start : stop : step
- an integer
- or a tuple of slice objects and integers

**``2 - Advanced indexing:``** Advanced indexing is triggered when obj is –

- an ndarray of type integer or Boolean
- or a tuple with at least one sequence object
- is a non tuple sequence object

For more information, please visit [INDEXING SOURCE](https://www.geeksforgeeks.org/numpy-indexing/)


[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://numpy.org/doc/stable/reference/arrays.indexing.html),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://pandas.pydata.org/pandas-docs/version/1.2.4/user_guide/indexing.html),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=9nbBTaz2qXI) &
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Bracket Indexing & Selection</p>

<a id="1.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
arr[8]  # 8. indexteki elemanı verir.

8

In [ ]:
arr[-3]  # -3. index teki eleman

8

In [ ]:
arr[1:5]  # 1-5 arasındaki indexte yer alan elemanlar

array([1, 2, 3, 4])

In [ ]:
arr[1::2]  # 1'den başlayıp 2 adım aralığı ile tek indexlere karşılık gelen elemanlar

array([1, 3, 5, 7, 9])

In [ ]:
arr[::2]  # 0'den başlayıp 2 adım aralığı ile çift indexlere karşılık gelen elemanlar 

array([ 0,  2,  4,  6,  8, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Indexing a 2D Array (Matrices)</p>

<a id="1.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row, col]</b>.<br> 
It's usually recommended using the comma notation for clarity.</p>

![image.png](https://i.ibb.co/pvdHbBm/numpy-index.png)

![image-2.png](https://i.ibb.co/jJPp6hk/numpy-indexing2.png)

[SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Fmedium.com%2F%40msjahid%2Fnumpy-array-indexing-slicing-23b70abb8433&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAk), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fiq.opengenus.org%2F2d-array-in-numpy%2F&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAp)<br>

In [ ]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# İki boyutlu arraylerde indexleme yapılırken önce satır, sonra sütun sayıları yazılır.

arr_2d[1]  # sadece tek index değeri belirtirsek o indexe karşılık gelen satırı getirir. 

array([20, 25, 30])

In [ ]:
arr_2d[1,1]  # veya arr_2d[1][1]   1. satır ve 1. sütundaki eleman

25

In [ ]:
arr_2d[1][1]  # 1. satır ve 1. sütundaki eleman

25

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Slicing a 2D Array (Matrices)</p>

<a id="1.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you know how to select subsets of Python lists, you know most of what you need to know about ndarray slicing. The elements of the array being indexed that correspond to the elements of the indexing object are returned in a new array. The most important aspect of indexing is to remember that there is more than one dimension, and the indexing method should be able to handle these other dimensions.

![image-2.png](https://i.ibb.co/64DGhj7/Numpy-index.jpg)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F16096753%2Fpython-array-slicing-how-can-2d-array-slicing-be-implemented&psig=AOvVaw0cHqeY-itYpRm19imsEBuR&ust=1644054927553000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCNiUt4vk5fUCFQAAAAAdAAAAABAD)

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# İki boyutlu arraylerde slicelamada da önce satır, sonra sütun aralıkları yazılmalıdır.

arr_2d[:2,1:]  # Baştan ikinci indexe kadar olan satırlar ile bu satırların baştan 2. indexine kadar olan sütunlarını verir.

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2,:2]  # Bikinci satırın baştan 2. indexine kadar olan kısmını verir.

array([35, 40])

In [ ]:
arr_2d[1,:1] = 55  # Bu şekilde slicelama ile aldığımız parçadaki değerleri kalıcı olarak başka bir değer ile değiştirebiliriz.

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [55, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1,:1] = 5.5  # float değer atadığınızda arrayin default değeri int olduğu için int'a çevirerek atar.

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [ 5, 25, 30],
       [35, 40, 45]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Fancy Indexing</p>

<a id="1.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once [SOURCE](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.). In Fancy Indexing, we pass array of indices instead of single scalar(numbers) to fetch elements at different index points. Remember that the shape of the output depends on the shape of the index arrays rather than the shape of the array being indexed. [SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftahamaddam.com%2Fcoding%2Fnumpy%2Fnumpy-fancy-indexing%2F&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAD), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F52485840%2Fnumpy-fancy-indexing-with-tuples%3Frq%3D1&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAO), [VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [ ]:
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# Aynı anda farklı kolon ve/veya sütunları/değerleri seçmek için fancy indexing kullanılır.

v[[1, 3, 5]]  # Ör: tek boyutlu array de 1, 3 ve 5. indexteki değerleri getirir.

array([ 3,  9, 15])

In [ ]:
arr2d = np.zeros((10,10), dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
for i in range(len(arr2d)):
    arr2d[i]=i

arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [ ]:
arr2d[2]  # arr2d arrayinin 2. satırı

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Fancy indexing allows the following

In [ ]:
arr2d[[1,3,5]]  # arr2d arrayinin 1, 3, 5. satırı 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
arr2d[[7,5,2]]  # arr2d arrayinin 7, 5, 2. satırı (yazdığımız sırayla)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

<h3>any_array[[row indices], [column indices]]</h3>

In [ ]:
jj = np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# İki boyutlu arraylerde fancy index yöntemiyle satır indexleri ve sütun indexleri de belirtilerek noktasal değerlere ulaşılabilir.

jj[[1,2],[0,3]]  # 1. satırın 0. elemanı, 2. satırın 3. elemanı

array([ 5, 12])

In [ ]:
jj[[1,2,0],[0,3,2]]  # 1. satırın 0. elemanı, 2. satırın 3. elemanı, 0. satırın 2. elemanı

array([ 5, 12,  3])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Index*** & ***Fancy Index*** Together</p>

<a id="1.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>



In [ ]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# Bazen bascin index ile fancy index metodu birlikte kullanılabilir.

jj[1,[1,3]]  # 1. satırın 1. elemanı, 1. satırın 3. elemanı    

array([6, 8])

In [ ]:
# veya 

jj[[1],[1,3]]  # satır indexi köşeli parantez içinde de yazılabilir.

array([6, 8])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Slicing*** & ***Fancy Index*** Together</p>

<a id="1.6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


In [ ]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# Basic slicing ve fancy index te birlikte kullanılabilir.

jj[:,[1,3]]  # tüm satırların 1. ve 3. sütunları

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [ ]:
jj[1:3,[1,3]]  # 1-3. satırların 1. ve 3. sütunları

array([[ 6,  8],
       [10, 12]])

In [ ]:
jj[1:3,1:3]  # 1-3. satırların 1-3. sütunları

array([[ 6,  7],
       [10, 11]])

In [ ]:
jj[1:,1:3]  # 1. satır ve sonrasının 1-3. sütunları

array([[ 6,  7],
       [10, 11],
       [14, 15]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">More Indexing Help</p>

<a id="1.7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png)

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fscipy-lectures.org%2Fintro%2Fnumpy%2Farray_object.html&psig=AOvVaw21eb1iMrmWndUhejWXLkY-&ust=1644056657663000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCICAqr_q5fUCFQAAAAAdAAAAABAD)

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views. [SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Selection on a Condition</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# bir array'e bir condition uygulandığında arrayin elemanlarının teker teker bu koşulu sağlayıp sağlamadığı
# kontrol edilerek array sayısı kadar boolean değer içeren bir array oluşturulur.
# Ör:

arr > 4  # arr nin elamanları için bu koşul kontrol edilerek uyanlar için True, uymayanlar için False değer içeren bir array elde ettik.

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
arr[arr > 4]  # bu koşulu [] içinde arr'nin yanına yazdığımızda bu koşulu sağlayan elemanlarını içeren bir array elde ederiz.

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[(arr < 3) | (arr > 7)]  # bazen birden fazla condition da uygulamak gerekebilir.

array([ 0,  1,  2,  8,  9, 10])

In [ ]:
arr[(arr < 3) | (arr > 7) & (arr!=9)]

array([ 0,  1,  2,  8, 10])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Broadcasting</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy arrays differ from a normal Python list because of their ability to broadcast [SOURCE](https://numpy.org/doc/stable/user/theory.broadcasting.html).<br>

**``Broadcasting``** is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size [SOURCE](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20is%20the%20name%20given,a%20different%20shape%20or%20size.&text=Subject%20to%20certain%20constraints%2C%20the,that%20they%20have%20compatible%20shapes.).<br>

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is **``broadcast``** across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation [SOURCE](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).<br> 

Broadcasting is an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays (eg per-element aritmetic) [SOURCE01](https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73), [SOURCE02](https://towardsdatascience.com/a-numpy-affair-broadcasting-ead20d9661f).<br>

**NumPy Broadcasting Limitations**<br>
Broadcasting is a very easy and handy tool when working with Numpy arrays. Although, there are many rules and restrictions to perform the operations.

There are constraints on the dimension and shape of the arrays. We can perform broadcasting in cases where both the arrays have the same shape or only if either of the two has a size of 1. Also, we have to consider the dimensions in reverse order. We count it from the trailing dimension [SOURCE](https://data-flair.training/blogs/numpy-broadcasting/).<br>

Be informed about the discussion on [When broadcasting is a bad idea? (numpy)](https://stackoverflow.com/questions/47309818/when-broadcasting-is-a-bad-idea-numpy) at Stackoverflow.

More Sources: [SOURCE01](https://inblog.in/Broadcasting-in-Numpy-A-Complete-Guide-jfKy2vzHiY), [SOURCE02](https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations), [SOURCE03](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/), [SOURCE04](https://www.askpython.com/python-modules/numpy/numpy-broadcasting), [SOURCE05](https://stackoverflow.com/questions/32832923/numpy-what-is-broadcasting), [SOURCE06](https://stackoverflow.com/questions/61090539/how-can-i-use-broadcasting-with-numpy-to-speed-up-this-correlation-calculation), [SOURCE07](https://stackoverflow.com/questions/68185016/numpy-broadcasting-two-arrays-of-different-shape-to-matrix), [SOURCE08](https://stackoverflow.com/questions/50569344/broadcasting-using-numpys-sum-function)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[:5] = 77  # arrayin belirli bir bölümünü alıp değerlerini değiştirebiliriz.

In [ ]:
arr

array([77, 77, 77, 77, 77,  5,  6,  7,  8,  9, 10])

Now **``note``** that the changes also occur in our original array!

In [ ]:
arr = np.arange(11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_slice = arr[:6]

arr_slice

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr_slice[:] = 55
arr_slice

array([55, 55, 55, 55, 55, 55])

In [ ]:
arr  # arr den kopyaladığım arrayde yaptığım değişiklikler orjinal arrayi de değiştirir.

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

In [ ]:
# Bunu engellemek için copy() fonksiyonu ile arrayin kopyasını alarak çalışmalıyız.

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#  arrayin kopyasını alarak kopyası üzerinden işlem yaparsanız orjinal arrayde yaptığınız değişiklikler gerçekleşmez.

arr_copy=arr.copy()
arr_copy

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:6] = [0,1, 2, 3, 4, 5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Operations</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

![image.png](https://i.ibb.co/n65mpTL/numpy-operations.png)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Arithmetic Operations</p>

<a id="4.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr  # bir array başka bir array ile toplanabilir. Bu durumda arraylerin shape leri uyumlu olmalı. element-wise işlem yapar.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr - arr  # bir array başka bir arrayden çıkarılabilir.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr # bir array başka bir array ile çarpılabilir.

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr / arr # bir array başka bir arraye bölünebilir.

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / arr  # bir sayıyı bir arraye bölebilirsiniz.

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr ** 2  # bir arrayin istediğiniz kuvvetini alabilirsiniz. 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [ ]:
arr + 1  # bir arrayi başka bir sayı ile toplayabilirsiniz.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr -5  # bir arrayden başka bir sayıyı çıkartabilirsiniz.

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
arr * 7  # bir arrayi başka bir sayı ile çarpabilirsiniz.

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

In [ ]:
arr ** arr  # bir arrayin başka bir array ile kuvvetini alabilirsiniz.

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [ ]:
np.subtract(arr, 1)  # np.subtract()  fonksiyonu içine yazılan arrayleri birbirinden çıkarır. Veya bir array'den bir sayıyı da çıkarabilirsiniz.

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.subtract(1, arr)  # np.subtract()  fonksiyonu bir sayıdan bi arrayi de çıkarabilirsiniz.

array([ 1,  0, -1, -2, -3, -4, -5, -6, -7, -8])

In [ ]:
np.add(2, arr)  # np.add() fonksiyonu ile bir array ile bir sayı/arrayi toplayabilirsiniz.

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.divide(arr, 2)  # np.divide() fonksiyonu ile bir arrayi  bir sayı/arraye bölebilirsiniz.

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.divide(2, arr)

array([       inf, 2.        , 1.        , 0.66666667, 0.5       ,
       0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222])

In [ ]:
np.multiply(arr, 3)  # np.multiply() fonksiyonu ile bir array ile bir sayı/arrayi çarpabilirsiniz.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.power(arr,4)  # np.power() fonksiyonu ile bir arrayin bir sayı/array kuvvetini alabilirsiniz.

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

In [ ]:
np.mod(arr, 2)  # np.mod() fonksiyonu ile bir array ile bir sayı/arrayin modulus(kalan değer) bulabilirsiniz.

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [ ]:
np.mod(arr[6], 2)  # arrayin sadece tek bir elemanı için veya bir bölümü için de bu fonksiyonları kullanabilirisiniz.

0

In [ ]:
np.absolute(-9)  # negatif bir sayının mutlak değerini almak için

9

In [ ]:
np.abs(-9)  # negatif bir sayının mutlak değerini almak için

9

In [ ]:
np.abs(10-arr)  # bir arrayin elemanlarının mutlak değerini almak için

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)  # bir arrayin elemanlarının karekökünü almak için

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)  # bir arrayin elemanlarının exponansiylini almak için

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)  # bir arrayin elemanlarının sinusunu almak için

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.sin(np.pi/2)

1.0

In [ ]:
np.tan(np.pi/4)

0.9999999999999999

In [ ]:
np.log(arr)  # bir arrayin elemanlarının logaritmasını almak için

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.log10(arr)  # bir arrayin elemanlarının log10'unu almak için

array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Universal Array Functions</p>

<a id="4.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

![image.png](https://i.ibb.co/QYWBrtK/numpy-operations1.png)

[SOURCE01](https://medium.com/swlh/universal-functions-ufuncs-a-weapon-of-numpy-b8d0145a3808), 
[SOURCE02](https://www.brainstobytes.com/hands-on-numpy-universal-functions-and-array-oriented-programming/)




#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
v = np.array([1, 1, 2, 2, 3, 3, 3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [ ]:
np.mean(v)  # arrayin ortalaması

2.142857142857143

In [ ]:
v.mean() # arrayin ortalaması

2.142857142857143

In [ ]:
np.median(v)  # veya np.percentile(v, 50)  # arrayin medyanı

2.0

In [ ]:
np.percentile(v, 50)  # arrayin medyanı 

2.0

In [ ]:
v.median()  # bu şekilde çalışmaz. sadece np.median() olarak çalışır.

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
v.std()  # arrayin standart sapması

0.8329931278350429

In [ ]:
v.var()  # arrayin varyasyonu

0.6938775510204082

In [ ]:
v.sum()  # arrayin toplamı

15

In [ ]:
# random olarak üretilen değerlerle tekrar çalışmak istediğinizde aynı değerlere ulaşmak için bu yöntem kullanılır.

np.random.seed(100)
arr= np.random.randn(3,5)
arr

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079],
       [ 0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081]])

In [ ]:
np.corrcoef(arr)  # bir arrayin correlation coefficient ının bulmak için

array([[ 1.        , -0.59546206,  0.21180175],
       [-0.59546206,  1.        ,  0.33872371],
       [ 0.21180175,  0.33872371,  1.        ]])

In [ ]:
v. min()  # arraydeki min. değeri bulmak için

1

In [ ]:
v. max()  # arraydeki max. değeri bulmak için

3

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Statistical Calculations</p>

<a id="4.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Statistics is concerned with collecting and then analyzing that data. It includes methods for collecting the samples, describing the data, and then concluding that data. NumPy is the fundamental package for scientific calculations and hence goes hand-in-hand for NumPy statistical Functions.

NumPy contains various statistical functions that are used to perform statistical data analysis. These statistical functions are useful when finding a maximum or minimum of elements. It is also used to find basic statistical concepts like standard deviation, variance, etc.

NumPy is equipped with the following statistical functions:

**``np.amin(arr)``** This function determines the minimum value of the element along a specified axis.<br>
**``np.amax(arr)``** This function determines the maximum value of the element along a specified axis.<br>
**``arr.min()``** Returns minimum value of arr<br>
**``arr.max(axis=0)``** Returns maximum value of specific axis<br>
**``np.mean(arr, axis=0)``** It determines the mean value of the data set.<br>
**``np.median(arr)``** It determines the median value of the data set.<br>
**``np.std(arr, axis=1)``** It determines the standard deviation.<br>
**``np.var(arr)``** It determines the variance.<br>
**``np.ptp(arr)``** It returns a range of values (maximum - minimum) along an axis.<br>
**``np.average(arr)``** It determines the weighted average.<br>
**``np.percentile(arr)``** It determines the nth percentile of data along the specified axis.<br>
**``np.corrcoef(arr)``** Returns correlation coefficient of array

More Sources: [SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/), [SOURCE02](https://python-tricks.com/statistical-functions-in-numpy/), [SOURCE03](https://numpy.org/doc/stable/reference/routines.statistics.html), [SOURCE04](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), [SOURCE05](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), [SOURCE06](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), [SOURCE07](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE08](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE09](https://www.codecademy.com/learn/intro-statistics-numpy)

In [ ]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
np.amin(arr, axis=0)  # axis=0 boyunca min değerleri döndürür

array([0, 1, 2, 3, 4])

In [ ]:
np.min(arr, axis=0) # axis=0 boyunca min değerleri döndürür

array([0, 1, 2, 3, 4])

In [ ]:
np.amax(arr, axis=1)  # axis=1 boyunca max değerleri döndürür

array([ 4,  9, 14])

In [ ]:
np.mean(arr, axis=0)  # axis=0 boyunca meam değerleri döndürür

array([5., 6., 7., 8., 9.])

In [ ]:
np.std(arr, axis=1)  # axis=1 boyunca std değerleri döndürür

array([1.41421356, 1.41421356, 1.41421356])

In [ ]:
np.var(arr, axis=0)  # axis=1 boyunca var değerleri döndürür

array([16.66666667, 16.66666667, 16.66666667, 16.66666667, 16.66666667])

In [ ]:
np.percentile(arr, 25, axis=0)  # # axis=0 boyunca q1(%25) değerleri döndürür

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [ ]:
np.corrcoef(arr)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Official Tutorial</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of the NumPy Session - 02</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>
___