<a href="https://colab.research.google.com/github/ustab/NOTES-FROM-LECTURERS/blob/main/Recap_29Apr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
data= [1, 3, 5, 7, 9]
pd.DataFrame(data)

0
0  1
1  3
2  5
3  7
4  9

In [ ]:
pd.DataFrame(data, columns=["Col1"])

Col1
0     1
1     3
2     5
3     7
4     9

In [5]:
pd.DataFrame(data, index = ["A","B","C","D","E"], columns=["Col1"])

Col1
A     1
B     3
C     5
D     7
E     9

In [17]:
data = np.arange(1,24,2).reshape(3,4)
df = pd.DataFrame(data=data, index=['Abi','Bibi','Cici'], columns=["var1","var2","var3","var4"])
df

var1  var2  var3  var4
Abi      1     3     5     7
Bibi     9    11    13    15
Cici    17    19    21    23

In [25]:
s1 = np.random.randint(2, 10, size = 4)
s2 = np.random.randint(3, 10, size = 4)
s3 = np.random.randint(4, 15, size = 4)
s1, s2, s3

(array([8, 3, 3, 4]), array([4, 5, 8, 7]), array([ 4,  5, 12,  7]))

In [26]:
mydict  = {"var1":s1, "var2":s2, "var3":s3}
mydict

{'var1': array([8, 3, 3, 4]),
 'var2': array([4, 5, 8, 7]),
 'var3': array([ 4,  5, 12,  7])}

In [28]:
df= pd.DataFrame(mydict, index=['ali','veli','selami','necati'])
df

var1  var2  var3
ali        8     4     4
veli       3     5     5
selami     3     8    12
necati     4     7     7

In [29]:
df.head(45)

var1  var2  var3
ali        8     4     4
veli       3     5     5
selami     3     8    12
necati     4     7     7

In [30]:
df.tail(12)

var1  var2  var3
ali        8     4     4
veli       3     5     5
selami     3     8    12
necati     4     7     7

In [33]:
df.sample(2)

var1  var2  var3
veli       3     5     5
selami     3     8    12

In [36]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [37]:
df.median(axis=1)

ali       4.0
veli      5.0
selami    8.0
necati    7.0
dtype: float64

In [50]:
df.mean(axis=0)

var1    4.5
var2    6.0
var3    7.0
dtype: float64

In [47]:
df.mean(axis=1)

ali       5.333333
veli      4.333333
selami    7.666667
necati    6.000000
dtype: float64

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.index[2]

2

In [51]:
df.values[3]

array([4, 7, 7])

In [56]:
df.keys

<bound method NDFrame.keys of         var1  var2  var3
ali        8     4     4
veli       3     5     5
selami     3     8    12
necati     4     7     7>

In [57]:
df.values

array([[ 8,  4,  4],
       [ 3,  5,  5],
       [ 3,  8, 12],
       [ 4,  7,  7]])

In [ ]:
df.columns = ["new1","new2","new3"]
df

new1  new2  new3
0     4     7     6
1     5     3    13
2     5     6     8
3     5     4    14

In [61]:
df.index=[1,2,3]

Index(['ali', 'veli', 'selami', 'necati'], dtype='object')

In [ ]:
df.index = ["a","b","c","d"]
df

new1  new2  new3
a     4     7     6
b     5     3    13
c     5     6     8
d     5     4    14

In [ ]:
df.rename(index={"a":1, "b": 2}, inplace=True)
df

new1  new2  new3
1     4     7     6
2     5     3    13
c     5     6     8
d     5     4    14

In [66]:
df.shape

(4, 3)

In [70]:
df.shape[1]

3

In [ ]:
df.shape[1]

3

In [71]:
len(df)

4

In [72]:
df.size

12

In [73]:
df.ndim

2

In [74]:
df.count(axis=1)

ali       3
veli      3
selami    3
necati    3
dtype: int64

In [75]:
df.count(axis=0)

var1    4
var2    4
var3    4
dtype: int64

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df["new1"])

pandas.core.series.Series

In [ ]:
df[["new1"]]

new1
1     4
2     5
c     5
d     5

In [ ]:
"new2" in df

True

In [78]:
from numpy.random import randn

In [83]:
np.random.seed(101)
df=pd.DataFrame(randn(5,4), index="A B C D E".split(), columns="W X Y Z".split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[["Y"]]

Y
A  0.907969
B -0.848077
C  0.528813
D -0.933237
E  2.605967

In [ ]:
df[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df.drop(columns=df.columns[0:2]) 

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057
E  2.605967  0.683509

In [ ]:
data = np.random.randint(1, 40, size=(8, 4))
df = pd.DataFrame(data, columns = ["var1", "var2", "var3", 'var4'])
df

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [ ]:
df.loc[2:5]#satir uzerinde calisir 2 den 5 dahil satir esas alir

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23

In [ ]:
df.loc["2":"5"]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23

In [ ]:
df.iloc[2:5]

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11

In [ ]:
df

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [ ]:
df.index = 'a b c d e f g h'.split()  # index değerlerini değiştirmek için. aatama yapılan değerlerin uzunluğu ile df'in uzunluğu aynı olmalı
df

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df.iloc[1:4]

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [ ]:
df.loc["b":"e"]

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11

In [ ]:
df

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df.loc["d":"g","var2"] 

d    30
e    36
f    28
g    24
Name: var2, dtype: int32

In [ ]:
df.loc["d":"g"]["var2"] 

d    30
e    36
f    28
g    24
Name: var2, dtype: int32

In [ ]:
df.loc["d":"g"].var2

29.5

In [ ]:
type(df.loc["d":"g"].var2)

pandas.core.series.Series

In [ ]:
df.loc["d":"g"][["var2"]] 

var2
d    30
e    36
f    28
g    24

In [ ]:
df.loc["d":"g",["var2"]]

var2    29.5
dtype: float64

In [ ]:
df.loc["d":"g",["var2"]].loc["e"]

var2    36
Name: e, dtype: int32

In [ ]:
df.loc["d":"g",["var1", "var3"]]

var1  var3
d    34    25
e    20    31
f    21     9
g    27    38

In [ ]:
df

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df.loc[df["var2"] > 10]["var2"]

a    11
c    18
d    30
e    36
f    28
g    24
Name: var2, dtype: int32

In [ ]:
df["var2"] > 10

a     True
b    False
c     True
d     True
e     True
f     True
g     True
h    False
Name: var2, dtype: bool

In [ ]:
df.loc[df["var2"] > 10, ["var2"]]

var2
a    11
c    18
d    30
e    36
f    28
g    24

In [ ]:
df.loc[df["var2"] > 10, ["var2"]]

var2
a    11
c    18
d    30
e    36
f    28
g    24

In [ ]:
df.iloc[::-1,::-1]

var4  var3  var2  var1
h    29    19     3    10
g    23    38    24    27
f    23     9    28    21
e    11    31    36    20
d    37    25    30    34
c    16    12    18    13
b     1    16     8    19
a    10    39    11     8

In [ ]:
df.loc[(df["var2"] > 10) & (df["var3"]<30), ["var2", "var3"]]

var2  var3
c    18    12
d    30    25
f    28     9