<a href="https://colab.research.google.com/github/ustab/NOTES-FROM-LECTURERS/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import scipy.stats as stats
import pandas as pd


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
# numpy.random.normal() method
r = np.random.normal(size=1000)
print(r)

In [52]:
mean=np.mean(r)
print(mean)

0.009063563792010992


In [53]:
median=np.median(r)
print(median)

0.0017751858752356612


In [38]:
mode=stats.mode(r)
print(r)

[-0.5465722  -1.4364397  -1.90544714  0.66471977 -1.53183613]


In [54]:
std=np.std(r)
print(std)

1.0097846263578834


Compute the **mean**, **median**, and **mode**

In [55]:
mean =np.mean(r)
print(mean)
median =np.median(r)
print(median)
mode =stats.mode(r)
print(mode)

0.009063563792010992
0.0017751858752356612
ModeResult(mode=array([-2.88094653]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [56]:
min =np.min(r) 
print(min)
max =np.max(r)
print(max)
q1 =np.percentile(r, 25)
print(q1)
q3 =np.percentile(r, 75)
print(q3)
iqr =q3-q1
print(iqr)

-2.8809465319037098
3.3718022433051456
-0.6587398918970206
0.6723542085262044
1.331094100423225


Compute the **variance** and **standard deviation**

In [57]:
variance = np.var(r)
print(variance)
std_dev =np.std(r)

1.0196649916287301


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [58]:
skewness =stats.skew(r)
print(skewness)
kurtosis =stats.kurtosis(r)
print(kurtosis)

0.044846841418931846
-0.13754758760214258


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [60]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [69]:
y = np.array(np.arange(10))
print(y)

[0 1 2 3 4 5 6 7 8 9]


Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [74]:
pearsons_coefficient = np.corrcoef(x, y)
print(pearsons_coefficient)

[[1. 1.]
 [1. 1.]]


## Pandas Correlation Calculation

Run the code below

In [78]:
x = pd.Series(range(10, 20))
print(x)
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(y)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64


Call the relevant method  to calculate Pearson's r correlation.

In [80]:
r =x.corr(y)
print(r)

#veya

r=y.corr(x)
print(r)

0.7586402890911867
0.7586402890911869


OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [85]:
xint=64
yint=64
rho=stats.spearmanr( xint, yint)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [100]:
sns.load_dataset("tips")
#tips = sns.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [109]:
df = sns.load_dataset("tips")
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [115]:
import numpy as np
df=sns.load_dataset("tips")

In [124]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns